/* 
 * File:   hc.c
 * Author: Ben Preece
 *
 * Created on August 11, 2010, 2:53 PM
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern void init();
extern void parse_args(int argc, char** argv);
extern void compile_input();

FILE *input = NULL;
FILE *output = NULL;

/*
 * 
 */
int main(int argc, char** argv)
{
    parse_args(argc, argv);
    compile_input();

    return (EXIT_SUCCESS);
}

void parse_args(int argc, char** argv)
{
    input = stdin;
    output = stdout;

    if (argc > 1) {
        input = fopen(argv[1], "r");
        if (input == NULL) {
            fprintf(stderr, "Unable to open \"%s\"", argv[1]);
            exit(-1);
        }
    }

    if (argc > 2) {
        output = fopen(argv[2], "w");
        if (output == NULL) {
            fprintf(stderr, "Unable to open \"%s\"", argv[2]);
            if (input != stdin) {
                fclose (input);
            }
            exit(-1);
        }
    }
}

#define BUF_SIZE 1001
#define HTML_MODE 0
#define C_MODE 1
char *start_html = "/***";
char *end_html = "***/";
char *start_expr = "<?=";
char *end_expr = "?>";

void compile_input()
{
    char *s, *t, *z, *z1, *z2, *z3, *z4;

    // start in html mode
    int mode = C_MODE;

    fprintf(output, "/*\n");
    fprintf(output, " * This file was auto-generated by hc.  Do not modify by hand.\n");
    fprintf(output, " */\n\n");

    char line[BUF_SIZE];
    while (fgets(line, BUF_SIZE, input) ) {
        // remove terminating newlines, if any
        t = strchr(line, '\0');
        if (t != NULL && t > line) {
            while (t[-1] == '\n' || t[-1] == '\r') {
                *--t = '\0';
            }
        }
        // check for empty line
        if (*line == '\0') {
            fprintf(output, "\n");
            continue;
        }

        s = line;
        while (s != NULL && *s != '\0') {
            switch (mode) {
                case C_MODE:
                    /*
                     * This part is easy.  Just dump C code until we get to
                     * the HTML.
                     */
                    z = strstr(s, start_html);
                    if (z == NULL) {
                        fprintf(output, "%s\n", s);
                        s = NULL;  // done with this line
                    } else {
                        fprintf(output, "%.*s\n", (z-s), s);
                        s = z + strlen(start_html);
                        mode = HTML_MODE;
                    }
                    break;
                case HTML_MODE:
                    /*
                     * We need to look for both the end of HTML, and also for
                     * the start of any embedded C expressions
                     */
                    z1 = strstr(s, end_html);
                    z2 = strstr(s, start_expr);
                    if (z1 == NULL && z2 == NULL) {
                        // the whole line is HTML -- need to escape any '\\' or '\"'
                        fprintf(output, "    printf(\"%%s\\n\", \""); // start the printf statement
                        while ((z4 = strpbrk(s, "\\\"")) != NULL) {
                            fprintf(output, "%.*s", (z4 - s), s);
                            fprintf(output, "\\%c", *z4);
                            s = z4 + 1;
                        }
                        if (*s != '\0') {
                            fprintf(output, "%s", s);
                        }
                        fprintf(output, "\");\n");  // terminate the printf statement
                        s = NULL;
                    } else if (z1 != NULL && (z2 == NULL || z1 < z2)) {
                        // we've found the end of HTML
                        fprintf(output, "    printf(\"%%s\\n\", \"%.*s\");\n", (z1 - s), s);
                        s = z1 + strlen(end_html);
                        mode = C_MODE;
                    } else {
                        // we've found a C-expression
                        // find the end of the C-expression -- must be on same line
                        z3 = strstr(z2, end_expr);
                        if (z3 == NULL) {
                            fprintf(stderr, "=== Unterminated C-expression: %s ===\n", z2);
                            exit(-1);
                        }
                        // emit the starting HTML -- need to escape any '\\' or '\"'
                        fprintf(output, "    printf(\"%%s\", \""); // start the printf statement
                        while ((z4 = strpbrk(s, "\\\"")) != NULL && z4 < z2) {
                            fprintf(output, "%.*s", (z4 - s), s);
                            fprintf(output, "\\%c", *z4);
                            s = z4 + 1;
                        }
                        if (s < z2) {
                            fprintf(output, "%.*s", (z2 - s), s);
                        }
                        fprintf(output, "\");\n");  // terminate the printf statement
                        // emit the C-expression
                        z2 += strlen(start_expr);
                        fprintf(output, "    printf(\"%%s\", %.*s);\n", (z3 - z2), z2);
                        // continue with the rest of the HTML
                        s = z3 + strlen(end_expr);
                    }
                    break;
                default:
                    fprintf(stderr, "=== Something is very wrong at line %d ===\n", __LINE__);
                    break;
            }
        }
    }
}
